# Assignment

Import numpy as np

In [1]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [4]:
list1=[1,2,3,4,5]
num=np.array(list1)
num

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => [[1,2,3],[4,5,6],[7,8,9]]

Convert it into numpy array and print it

In [6]:
list2=np.arange(1,10)
list2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [9]:
list3=np.arange(1,18,2)
list3.reshape(3,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [15]:
ranarr= np.random.randint(0,10,10)
ranarr

array([9, 3, 0, 8, 6, 1, 5, 5, 0, 9])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [18]:
list4=np.arange(1,6)
list4=list4.reshape(5,1)
list4

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [19]:
list4.shape

(5, 1)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [25]:
list5=np.arange(0,10,1)
print("3rd element {}\n4th element {}\n9th element {}".format(list5[3],list5[4],list5[9]))

3rd element 3
4th element 4
9th element 9


Print alternate elements of that array

In [28]:
for i in range(0,10,2):
    print(list5[i])

0
2
4
6
8


Change last 3 elements into 100 using broadcasting and print

In [30]:
list5[-3:]=100
list5

array([  0,   1,   2,   3,   4,   5,   6, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [51]:
list6= np.random.randint(0,50,25)
list6=list6.reshape(5,5)
print(list6)


[[10 20 44 40 28]
 [27 15 24 33 25]
 [11 10 14  7  3]
 [39 28 46 44 29]
 [25 35 12  9  4]]


In [52]:
print(list6[1:4,1:4])

[[15 24 33]
 [10 14  7]
 [28 46 44]]
